/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_cpptest_CppActivity */

#ifndef _Included_com_cpptest_CppActivity
#define _Included_com_cpptest_CppActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_cpptest_CppActivity
 * Method:    codeTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cpptest_CppActivity_codeTest (JNIEnv *);

#ifdef __cplusplus
}
#endif
#endif
